export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USER_NAME = "GET_USER_NAME";
export const GET_ALL_RECIPES = "GET_ALL_RECIPES";
export const GET_ALL_RECIPES_BY_USER = "GET_ALL_RECIPES_BY_USER";
export const GET_RECIPE_BY_ID = "GET_RECIPE_BY_ID";
